import dash
from dash import html, dcc
import dash_bootstrap_components as dbc


# ------------------------------------
# Register page
# ------------------------------------
dash.register_page(__name__, path="/metrics-info", name="Metrics Info")

# ------------------------------------
# Layout
# ------------------------------------

layout = dbc.Container(
    [
        html.H1("Metrics Information"),
        html.P("Below there is information about what the different kpi card headings represent."),  
        dbc.Row([
          dbc.Col([

        dbc.Card([
          dbc.CardHeader("Definitions"),
          dbc.CardBody([
          html.Ul([
                html.Li("Total Datasets Reviewed: The total datasets reviewed by DPS. This includes datasets that were accepted and rejected for preservation."),
                html.Li("Total Datasets Processed: Total number of dataset inf FRDR that have gone through preservation processing."),
                html.Li("Total AIPs: The total number of AIPs produced as a result of preservation processing. There isn't a 1:1 ratio between datasets processed and AIPs because of the older versioning system and older datasets have been reprocessed. For example, if dataset 9 had 3 versions, each version gets an AIP."),
                html.Li("Total Storage: Reflects the total storage space is being taken by AIPs in long-term storage at SciNet."),
                html.Li("Published Datasets: For the purposes of this dashboard, published datasets includes datasets that are publically available and those under embargo."),
              ]),   
            ])
          ]),
        ], width=6, 
      ),    
      dbc.Col([
          dbc.Card ([
            dbc.CardHeader("Resources"),  
            dbc.CardBody([
                html.Ul([
                  html.Li([html.A("Stats and Metrics workflow", href="https://docs.google.com/document/d/1K4GMgWtmmFbpB7fMwoxokx6fSnDA3OtQLj5P7wU7iqc/edit?usp=drive_link", target="_blank"), " - Updates in progrss."]),
                  html.Li([html.A("Full Metrics Dashboard", href="https://docs.google.com/spreadsheets/d/1O3nWG19H64kFMvWK2FWbrUatx_vm01gKzSL7Vo-O40A/edit?usp=sharing", target="_blank"), " - Includes the underlining data for the dashboard."]),
                  html.Li([html.A("pres_res_formats", href="https://github.com/Alliance-RDM-GDR/pres_res_formats", target="_blank"), " - GitHub repository containing scripts for format stats and FPR creation. Updates in progress."]),
                  html.Li([html.A("pres_res_metrics", href="https://docs.google.com/spreadsheets/d/1O3nWG19H64kFMvWK2FWbrUatx_vm01gKzSL7Vo-O40A/edit?usp=sharing", target="_blank"), " - GitHub repository containing scripts for processing and FRDR metrics. Updates in progress."]), 
                  html.Li([html.A("pres_res_borealis_frdr_formats", href="https://github.com/Alliance-RDM-GDR/pres_res_borealis_frdr_formats", target="_blank"), " - GitHub repository containing scripts for Borealis format analysis and comparision to FRDR formats. Updates in progress."]),
                  html.Li([html.A("pres_res_format_browser", href="https://github.com/Alliance-RDM-GDR/pres_res_format_browser", target="_blank"), " - GitHub repository containing scripts for a lightweight application to search for formats and the related content generated by DPS including sigantures, CRDC mapping, summary and analysis, and much more. In development."]),
                  html.Li([html.A("pres_res_dashboard", href="https://github.com/Alliance-RDM-GDR/pres_res_dashboard", target="_blank"), " - GitHub repository for this dashboard."]),
                ]),   
            ])
          ])
        ],  width=6),
    ], className="mb-4"),
    dbc.Row([
          dbc.Col([
            dbc.Card ([
              dbc.CardHeader("Future Developments"),  
              dbc.CardBody([
                 html.Ul([
                  html.Li("The redesign of the funder page with retention requirements to faciliate retention decisions for datasets."),
                  html.Li("The redesign of the licenses page to include custom licenses."),
                  html.Li("The redesign of the CRDC-Format mapping."),
                  html.Li("The reworking of the geographic distribution of research topics to include areas outside of Canada."),
                  html.Li("The inclusion of common preservation justifications"),
                  html.Li("The addition of a journal information to help with appraisal review."),
                  html.Li("The addition of more information from the appraisal matrix including documentation ranking for dataset readmes."),
                  html.Li("The remapping of CRDC codes when the new version is released."),
                  html.Li("The addition of time estimates for preservation work based on dataset type."),
                  html.Li("The inclusion of benchmarking results from yearly DPS analysis using DPC RAM."),
                   html.Li("The inclusion of integrity checking results and other error stats."),
                  html.Li("As DPS expand more information may be added."),
                ]),   
    
              ])
    
            ])
          ], width=12 )
    
        ]),
    ],
    fluid=True,
)
